a = input("Enter the first number: ")
a = float(a)
b = input("Enter the second number: ")
b = float(b)
print("addition: ", a+b)
print("subtraction: ", a-b)
print("multiplication: ", a*b)
print("division: ", a/b)